services:
  node_msg_broker:
    container_name: node_msg_broker
    build:
        context: ./controller_components/node_msg_broker/
        dockerfile: Dockerfile
    command: ./node_msg_broker &
    ports:
      - "192.168.53.11:5554:5554"
      - "192.168.53.11:5555:5555"
      - "192.168.53.11:5556:5556"
      - "192.168.53.11:5557:5557"

  aic_msg_broker:
    container_name: aic_msg_broker
    build:
        context: ./controller_components/aic_msg_broker/
        dockerfile: Dockerfile
    command: ./aic_msg_broker &
    ports:
      - "192.168.53.11:6554:6554"
      - "192.168.53.11:6555:6555"
      - "192.168.53.11:6556:6556"
      - "192.168.53.11:6557:6557"

  aic_register:
    container_name: aic_register
    build:
        context: ./controller_components/register/
        dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: python3 register.py
    volumes:
      - ./controller_components/register/:/register
    ports:
      - "192.168.53.11:5558:5558"
    depends_on:
      - redis
      - node_msg_broker
      - aic_msg_broker

  redis:
    image: redis:latest
    volumes:
      - ./data:/data
